name: Build Commit

on:
  push:
    branches:
      - master
    paths:
      - src/**
      - Cargo.toml
      - Cargo.lock
      - .github/workflows/build.yml

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build Commit - ${{ matrix.platform.release_for }}
    strategy:
      matrix:
        platform:
          - release_for: Linux-x86_64-gnu
            os: ubuntu-20.04
            target: x86_64-unknown-linux-gnu
            bin: red_oxide
            name: red_oxide-Linux-x86_64-gnu
            command: build
    runs-on: ${{ matrix.platform.os }}
    steps:
      - name: Checkout Source code
        uses: actions/checkout@v4
      - name: Cache cargo & target directories
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.platform.release_for }}
      - name: Install musl-tools on Linux
        run: sudo apt-get update --yes && sudo apt-get install --yes musl-tools
        if: contains(matrix.platform.name, 'musl')
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: ${{ matrix.platform.command }}
          target: ${{ matrix.platform.target }}
          args: "--locked --release"
          strip: true
      - name: Upload Action Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform.name }}
          path: target/${{ matrix.platform.target }}/release/${{ matrix.platform.bin }}
